apiVersion: v1
kind: Service
metadata:
  name: authorization-server
  namespace: miniauth
spec:
  selector:
    app: authorization-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer